In [1]:
import pandas as pd
import numpy as np

In [2]:
training_one_hot = pd.read_csv('01_Data_Download_Preprocessing_onehotencoding.csv')

In [3]:
training_one_hot['date'] = pd.to_datetime(training_one_hot['S_2'])

In [4]:
training_one_hot['date'].describe()

count                          1107082
mean     2017-09-20 20:27:55.010884608
min                2017-03-01 00:00:00
25%                2017-06-15 00:00:00
50%                2017-09-23 00:00:00
75%                2017-12-29 00:00:00
max                2018-03-31 00:00:00
Name: date, dtype: object

In [5]:
april_2018 = pd.Timestamp('2018-04-01')
train_date_filtered = training_one_hot[training_one_hot['date']<=april_2018]

In [48]:
numerical_cols = train_date_filtered.select_dtypes(include=['int64','float64']).columns.tolist()

numerical_cols = [col for col in numerical_cols if col !='customer_ID' and col!='Unnamed: 0' and col!='target' and col!='date']

In [49]:
numerical_cols

['P_2',
 'D_39',
 'B_1',
 'B_2',
 'R_1',
 'S_3',
 'D_41',
 'B_3',
 'D_42',
 'D_43',
 'D_44',
 'B_4',
 'D_45',
 'B_5',
 'R_2',
 'D_46',
 'D_47',
 'D_48',
 'D_49',
 'B_6',
 'B_7',
 'B_8',
 'D_50',
 'D_51',
 'B_9',
 'R_3',
 'D_52',
 'P_3',
 'B_10',
 'D_53',
 'S_5',
 'B_11',
 'S_6',
 'D_54',
 'R_4',
 'S_7',
 'B_12',
 'S_8',
 'D_55',
 'D_56',
 'B_13',
 'R_5',
 'D_58',
 'S_9',
 'B_14',
 'D_59',
 'D_60',
 'D_61',
 'B_15',
 'S_11',
 'D_62',
 'D_65',
 'B_16',
 'B_17',
 'B_18',
 'B_19',
 'D_66',
 'B_20',
 'S_12',
 'R_6',
 'S_13',
 'B_21',
 'D_69',
 'B_22',
 'D_70',
 'D_71',
 'D_72',
 'S_15',
 'B_23',
 'D_73',
 'P_4',
 'D_74',
 'D_75',
 'D_76',
 'B_24',
 'R_7',
 'D_77',
 'B_25',
 'B_26',
 'D_78',
 'D_79',
 'R_8',
 'R_9',
 'S_16',
 'D_80',
 'R_10',
 'R_11',
 'B_27',
 'D_81',
 'D_82',
 'S_17',
 'R_12',
 'B_28',
 'R_13',
 'D_83',
 'R_14',
 'R_15',
 'D_84',
 'R_16',
 'B_29',
 'S_18',
 'D_86',
 'D_87',
 'R_17',
 'R_18',
 'D_88',
 'B_31',
 'S_19',
 'R_19',
 'B_32',
 'S_20',
 'R_20',
 'R_21',
 'B_33',
 'D_89',
 'R_22',
 'R_23',
 'D_91',
 'D_92',
 'D_93',
 'D_94',
 'R_24',
 'R_25',
 'D_96',
 'S_22',
 'S_23',
 'S_24',
 'S_25',
 'S_26',
 'D_102',
 'D_103',
 'D_104',
 'D_105',
 'D_106',
 'D_107',
 'B_36',
 'B_37',
 'R_26',
 'R_27',
 'D_108',
 'D_109',
 'D_110',
 'D_111',
 'B_39',
 'D_112',
 'B_40',
 'S_27',
 'D_113',
 'D_115',
 'D_118',
 'D_119',
 'D_121',
 'D_122',
 'D_123',
 'D_124',
 'D_125',
 'D_127',
 'D_128',
 'D_129',
 'B_41',
 'B_42',
 'D_130',
 'D_131',
 'D_132',
 'D_133',
 'R_28',
 'D_134',
 'D_135',
 'D_136',
 'D_137',
 'D_138',
 'D_139',
 'D_140',
 'D_141',
 'D_142',
 'D_143',
 'D_144',
 'D_145']

In [38]:
import pandas as pd
from functools import reduce

In [39]:
cat_feature = ['B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']

In [40]:
train_date_filtered

,Unnamed: 0,customer_ID,target,S_2,P_2,D_39,B_1,B_2,R_1,S_3,...,D_64_R,D_64_U,D_68_0.0,D_68_1.0,D_68_2.0,D_68_3.0,D_68_4.0,D_68_5.0,D_68_6.0,date
0,0,12c761e40348fa242de0356426fa9547f0feea34d1f57b...,0,2017-03-21,0.628534,0.004250,0.017667,0.815468,0.005736,0.265531,...,False,False,False,False,False,False,False,False,False,2017-03-21
1,1,12c761e40348fa242de0356426fa9547f0feea34d1f57b...,0,2017-04-21,0.669914,0.418321,0.354284,1.000587,0.009774,0.176196,...,False,False,False,False,False,False,False,False,False,2017-04-21
2,2,12c761e40348fa242de0356426fa9547f0feea34d1f57b...,0,2017-05-08,0.661933,0.003989,0.244867,1.008683,0.005743,0.169471,...,False,False,False,False,True,False,False,False,False,2017-05-08
3,3,12c761e40348fa242de0356426fa9547f0feea34d1f57b...,0,2017-06-14,0.644270,0.009351,0.017799,0.668398,0.003148,0.174020,...,False,False,False,False,True,False,False,False,False,2017-06-14
4,4,12c761e40348fa242de0356426fa9547f0feea34d1f57b...,0,2017-07-26,0.688055,0.002832,0.009458,0.779692,0.000870,0.174547,...,False,False,False,False,True,False,False,False,False,2017-07-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107077,1107077,f0defebbf6e79c14234a06c5b3522ee5914cb0f23fdd13...,0,2017-11-29,0.957207,0.003413,0.005511,0.811611,0.007821,NaN,...,True,False,False,False,False,False,False,False,True,2017-11-29
1107078,1107078,f0defebbf6e79c14234a06c5b3522ee5914cb0f23fdd13...,0,2017-12-30,0.826494,0.007873,0.009774,0.819318,0.007074,NaN,...,False,False,False,False,False,False,False,True,False,2017-12-30
1107079,1107079,f0defebbf6e79c14234a06c5b3522ee5914cb0f23fdd13...,0,2018-01-30,0.828001,0.002666,0.001569,0.815946,0.001636,NaN,...,False,False,False,False,False,False,False,True,False,2018-01-30
1107080,1107080,f0defebbf6e79c14234a06c5b3522ee5914cb0f23fdd13...,0,2018-02-27,0.825479,0.001338,0.006197,0.812589,0.000352,NaN,...,False,False,False,False,False,False,False,True,False,2018-02-27
1107081,1107081,f0defebbf6e79c14234a06c5b3522ee5914cb0f23fdd13...,0,2018-03-30,0.839816,0.006281,0.002410,0.818417,0.006255,NaN,...,False,False,False,False,False,False,False,True,False,2018-03-30

In [41]:
one_hot_encoded_cols = [col for col in train_date_filtered.columns if any(col.startswith(f"{prefix}_") for prefix in cat_feature)]

In [42]:
#comeback to this 
def reduce_memory_usage(df):
    for col in df.select_dtypes(include=['float64']).columns:
        df[col] = df[col].astype('float32')
    for col in df.select_dtypes(include=['int64']).columns:
        df[col] = df[col].astype('int32')
    return df

def aggregate_numerical_feature(df, feature, ref_date, customer_col='customer_ID', date_col='date'):
    windows = [3, 6, 9, 12]
    agg_list = []

    for window in windows:
        mask = (df[date_col] <= ref_date) & (df[date_col] > (ref_date - pd.DateOffset(months=window)))
        temp = df.loc[mask, [customer_col, feature]]

        grouped = temp.groupby(customer_col)[feature].agg([
            (f'{feature}Ave{window}', 'mean'),
            (f'{feature}Min{window}', 'min'),
            (f'{feature}Max{window}', 'max'),
            (f'{feature}Sum{window}', 'sum')
        ]).reset_index()

        grouped = reduce_memory_usage(grouped)
        agg_list.append(grouped)

    # Safe merging using loop (avoids deep recursion and memory spikes)
    df_agg = agg_list[0]
    for next_df in agg_list[1:]:
        df_agg = pd.merge(df_agg, next_df, on=customer_col, how='outer')

    # Latest value as of ref_date (April 2018)
    latest = df[df[date_col] == ref_date][[customer_col, feature]].rename(
        columns={feature: f'{feature}Apr{ref_date.year}'}
    )
    df_agg = pd.merge(df_agg, latest, on=customer_col, how='left')

    # Value from previous April
    prev_year_date = ref_date - pd.DateOffset(years=1)
    prev_year = df[df[date_col] == prev_year_date][[customer_col, feature]].rename(
        columns={feature: f'{feature}Apr{prev_year_date.year}'}
    )
    df_agg = pd.merge(df_agg, prev_year, on=customer_col, how='left')

    return reduce_memory_usage(df_agg)

In [43]:
def aggregate_one_hot_feature(df, feature, ref_date, customer_col='customer_ID', date_col='date'):
  
    # Define time windows in months
    windows = [6, 12]
    agg_list = []

    for window in windows:
        # Filter data within the time window
        mask = (df[date_col] <= ref_date) & (df[date_col] > (ref_date - pd.DateOffset(months=window)))

        # Only keep the necessary columns to reduce memory
        temp = df.loc[mask, [customer_col, feature]]

        # Group by customer and perform aggregations
        grouped = temp.groupby(customer_col)[feature].agg([
            (f'{feature}Response_Rate{window}', 'mean'),  # % of times it is 1 (response rate)
            (f'{feature}Ever_Response{window}', 'max')    # Was it ever 1?
        ]).reset_index()

        agg_list.append(grouped)

    # Merge all aggregations on customer_id
    if agg_list:
        df_agg = reduce(lambda left, right: pd.merge(left, right, on=customer_col, how='outer'), agg_list)
    else:
        df_agg = pd.DataFrame(columns=[customer_col])

    # Get the value for the feature as of ref_date
    latest = df[df[date_col] == ref_date][[customer_col, feature]].rename(
        columns={feature: f'{feature}Apr{ref_date.year}'}
    )

    # Merge latest value into the final aggregated dataframe
    df_final = pd.merge(df_agg, latest, on=customer_col, how='left')

    return df_final

In [44]:
one_hot_encoded_cols = [col for col in train_date_filtered.columns if any(col.startswith(f"{prefix}_") for prefix in cat_feature)]

In [45]:
# Helper function to reduce memory usage
def reduce_memory_usage(df):
    for col in df.select_dtypes(include=['float64']).columns:
        df[col] = df[col].astype('float32')
    for col in df.select_dtypes(include=['int64']).columns:
        df[col] = df[col].astype('int32')
    for col in df.select_dtypes(include=['object']).columns:
        if df[col].nunique() < df.shape[0] // 2:
            df[col] = df[col].astype('category')
    return df

# Aggregation for categorical (one-hot encoded) features
categorical_agg_list = []

for feature in one_hot_encoded_cols:
    print(f'Aggregating one-hot encoded feature: {feature}')
    agg_df = aggregate_one_hot_feature(train_date_filtered, feature, april_2018,
                                       customer_col='customer_ID', date_col='date')
    agg_df = reduce_memory_usage(agg_df)
    categorical_agg_list.append(agg_df)

# Safe merging using a loop instead of reduce
if categorical_agg_list:
    df_categorical_features = categorical_agg_list[0]
    for next_df in categorical_agg_list[1:]:
        df_categorical_features = pd.merge(df_categorical_features, next_df, on='customer_ID', how='outer')
else:
    df_categorical_features = pd.DataFrame()

Aggregating one-hot encoded feature: B_30_0.0
Aggregating one-hot encoded feature: B_30_1.0
Aggregating one-hot encoded feature: B_30_2.0
Aggregating one-hot encoded feature: B_38_1.0
Aggregating one-hot encoded feature: B_38_2.0
Aggregating one-hot encoded feature: B_38_3.0
Aggregating one-hot encoded feature: B_38_4.0
Aggregating one-hot encoded feature: B_38_5.0
Aggregating one-hot encoded feature: B_38_6.0
Aggregating one-hot encoded feature: B_38_7.0
Aggregating one-hot encoded feature: D_114_0.0
Aggregating one-hot encoded feature: D_114_1.0
Aggregating one-hot encoded feature: D_116_0.0
Aggregating one-hot encoded feature: D_116_1.0
Aggregating one-hot encoded feature: D_117_-1.0
Aggregating one-hot encoded feature: D_117_1.0
Aggregating one-hot encoded feature: D_117_2.0
Aggregating one-hot encoded feature: D_117_3.0
Aggregating one-hot encoded feature: D_117_4.0
Aggregating one-hot encoded feature: D_117_5.0
Aggregating one-hot encoded feature: D_117_6.0
Aggregating one-hot encoded feature: D_120_0.0
Aggregating one-hot encoded feature: D_120_1.0
Aggregating one-hot encoded feature: D_126_-1.0
Aggregating one-hot encoded feature: D_126_0.0
Aggregating one-hot encoded feature: D_126_1.0
Aggregating one-hot encoded feature: D_63_CL
Aggregating one-hot encoded feature: D_63_CO
Aggregating one-hot encoded feature: D_63_CR
Aggregating one-hot encoded feature: D_63_XL
Aggregating one-hot encoded feature: D_63_XM
Aggregating one-hot encoded feature: D_63_XZ
Aggregating one-hot encoded feature: D_64_-1
Aggregating one-hot encoded feature: D_64_O
Aggregating one-hot encoded feature: D_64_R
Aggregating one-hot encoded feature: D_64_U
Aggregating one-hot encoded feature: D_68_0.0
Aggregating one-hot encoded feature: D_68_1.0
Aggregating one-hot encoded feature: D_68_2.0
Aggregating one-hot encoded feature: D_68_3.0
Aggregating one-hot encoded feature: D_68_4.0
Aggregating one-hot encoded feature: D_68_5.0
Aggregating one-hot encoded feature: D_68_6.0

In [46]:
train_date_filtered.dtypes

Unnamed: 0              int64
customer_ID            object
target                  int64
S_2                    object
P_2                   float64
                    ...
D_68_3.0                 bool
D_68_4.0                 bool
D_68_5.0                 bool
D_68_6.0                 bool
date           datetime64[ns]
Length: 226, dtype: object

In [50]:
# Initialize output list
numerical_agg_list = []

# Loop through all numerical columns
for feature in numerical_cols:
    print(f'Aggregating numerical feature: {feature}')
    agg_df = aggregate_numerical_feature(train_date_filtered, feature, april_2018,
                                         customer_col='customer_ID', date_col='date')
    numerical_agg_list.append(agg_df)

# Merge all aggregated numerical features
if numerical_agg_list:
    df_numerical_features = numerical_agg_list[0]
    for next_df in numerical_agg_list[1:]:
        df_numerical_features = pd.merge(df_numerical_features, next_df, on='customer_ID', how='outer')
else:
    df_numerical_features =pd.DataFrame()

Aggregating numerical feature: P_2
Aggregating numerical feature: D_39
Aggregating numerical feature: B_1
Aggregating numerical feature: B_2
Aggregating numerical feature: R_1
Aggregating numerical feature: S_3
Aggregating numerical feature: D_41
Aggregating numerical feature: B_3
Aggregating numerical feature: D_42
Aggregating numerical feature: D_43
Aggregating numerical feature: D_44
Aggregating numerical feature: B_4
Aggregating numerical feature: D_45
Aggregating numerical feature: B_5
Aggregating numerical feature: R_2
Aggregating numerical feature: D_46
Aggregating numerical feature: D_47
Aggregating numerical feature: D_48
Aggregating numerical feature: D_49
Aggregating numerical feature: B_6
Aggregating numerical feature: B_7
Aggregating numerical feature: B_8
Aggregating numerical feature: D_50
Aggregating numerical feature: D_51
Aggregating numerical feature: B_9
Aggregating numerical feature: R_3
Aggregating numerical feature: D_52
Aggregating numerical feature: P_3
Aggregating numerical feature: B_10
Aggregating numerical feature: D_53
Aggregating numerical feature: S_5
Aggregating numerical feature: B_11
Aggregating numerical feature: S_6
Aggregating numerical feature: D_54
Aggregating numerical feature: R_4
Aggregating numerical feature: S_7
Aggregating numerical feature: B_12
Aggregating numerical feature: S_8
Aggregating numerical feature: D_55
Aggregating numerical feature: D_56
Aggregating numerical feature: B_13
Aggregating numerical feature: R_5
Aggregating numerical feature: D_58
Aggregating numerical feature: S_9
Aggregating numerical feature: B_14
Aggregating numerical feature: D_59
Aggregating numerical feature: D_60
Aggregating numerical feature: D_61
Aggregating numerical feature: B_15
Aggregating numerical feature: S_11
Aggregating numerical feature: D_62
Aggregating numerical feature: D_65
Aggregating numerical feature: B_16
Aggregating numerical feature: B_17
Aggregating numerical feature: B_18
Aggregating numerical feature: B_19
Aggregating numerical feature: D_66
Aggregating numerical feature: B_20
Aggregating numerical feature: S_12
Aggregating numerical feature: R_6
Aggregating numerical feature: S_13
Aggregating numerical feature: B_21
Aggregating numerical feature: D_69
Aggregating numerical feature: B_22
Aggregating numerical feature: D_70
Aggregating numerical feature: D_71
Aggregating numerical feature: D_72
Aggregating numerical feature: S_15
Aggregating numerical feature: B_23
Aggregating numerical feature: D_73
Aggregating numerical feature: P_4
Aggregating numerical feature: D_74
Aggregating numerical feature: D_75
Aggregating numerical feature: D_76
Aggregating numerical feature: B_24
Aggregating numerical feature: R_7
Aggregating numerical feature: D_77
Aggregating numerical feature: B_25
Aggregating numerical feature: B_26
Aggregating numerical feature: D_78
Aggregating numerical feature: D_79
Aggregating numerical feature: R_8
Aggregating numerical feature: R_9
Aggregating numerical feature: S_16
Aggregating numerical feature: D_80
Aggregating numerical feature: R_10
Aggregating numerical feature: R_11
Aggregating numerical feature: B_27
Aggregating numerical feature: D_81
Aggregating numerical feature: D_82
Aggregating numerical feature: S_17
Aggregating numerical feature: R_12
Aggregating numerical feature: B_28
Aggregating numerical feature: R_13
Aggregating numerical feature: D_83
Aggregating numerical feature: R_14
Aggregating numerical feature: R_15
Aggregating numerical feature: D_84
Aggregating numerical feature: R_16
Aggregating numerical feature: B_29
Aggregating numerical feature: S_18
Aggregating numerical feature: D_86
Aggregating numerical feature: D_87
Aggregating numerical feature: R_17
Aggregating numerical feature: R_18
Aggregating numerical feature: D_88
Aggregating numerical feature: B_31
Aggregating numerical feature: S_19
Aggregating numerical feature: R_19
Aggregating numerical feature: B_32
Aggregating numerical feature: S_20
Aggregating numerical feature: R_20
Aggregating numerical feature: R_21
Aggregating numerical feature: B_33
Aggregating numerical feature: D_89
Aggregating numerical feature: R_22
Aggregating numerical feature: R_23
Aggregating numerical feature: D_91
Aggregating numerical feature: D_92
Aggregating numerical feature: D_93
Aggregating numerical feature: D_94
Aggregating numerical feature: R_24
Aggregating numerical feature: R_25
Aggregating numerical feature: D_96
Aggregating numerical feature: S_22
Aggregating numerical feature: S_23
Aggregating numerical feature: S_24
Aggregating numerical feature: S_25
Aggregating numerical feature: S_26
Aggregating numerical feature: D_102
Aggregating numerical feature: D_103
Aggregating numerical feature: D_104
Aggregating numerical feature: D_105
Aggregating numerical feature: D_106
Aggregating numerical feature: D_107
Aggregating numerical feature: B_36
Aggregating numerical feature: B_37
Aggregating numerical feature: R_26
Aggregating numerical feature: R_27
Aggregating numerical feature: D_108
Aggregating numerical feature: D_109
Aggregating numerical feature: D_110
Aggregating numerical feature: D_111
Aggregating numerical feature: B_39
Aggregating numerical feature: D_112
Aggregating numerical feature: B_40
Aggregating numerical feature: S_27
Aggregating numerical feature: D_113
Aggregating numerical feature: D_115
Aggregating numerical feature: D_118
Aggregating numerical feature: D_119
Aggregating numerical feature: D_121
Aggregating numerical feature: D_122
Aggregating numerical feature: D_123
Aggregating numerical feature: D_124
Aggregating numerical feature: D_125
Aggregating numerical feature: D_127
Aggregating numerical feature: D_128
Aggregating numerical feature: D_129
Aggregating numerical feature: B_41
Aggregating numerical feature: B_42
Aggregating numerical feature: D_130
Aggregating numerical feature: D_131
Aggregating numerical feature: D_132
Aggregating numerical feature: D_133
Aggregating numerical feature: R_28
Aggregating numerical feature: D_134
Aggregating numerical feature: D_135
Aggregating numerical feature: D_136
Aggregating numerical feature: D_137
Aggregating numerical feature: D_138
Aggregating numerical feature: D_139
Aggregating numerical feature: D_140
Aggregating numerical feature: D_141
Aggregating numerical feature: D_142
Aggregating numerical feature: D_143
Aggregating numerical feature: D_144
Aggregating numerical feature: D_145

In [51]:
df_numerical_features

,customer_ID,P_2Ave3,P_2Min3,P_2Max3,P_2Sum3,P_2Ave6,P_2Min6,P_2Max6,P_2Sum6,P_2Ave9,...,D_145Ave9,D_145Min9,D_145Max9,D_145Sum9,D_145Ave12,D_145Min12,D_145Max12,D_145Sum12,D_145Apr2018,D_145Apr2017
0,000098081fde4fd64bc4d503a5d6f86a0aedc425c96f52...,0.447801,0.414444,0.477116,1.343404,0.453994,0.407172,0.560474,2.723962,0.472079,...,0.005859,0.001913,0.009131,0.052735,0.005499,0.001265,0.009131,0.065984,NaN,NaN
1,000445609ff2a39d2dd02484899affa5696210a95f6869...,0.976846,0.974383,0.978897,2.930539,0.972001,0.949051,0.986043,5.832008,0.971372,...,0.004471,0.000315,0.009732,0.040236,0.004402,0.000315,0.009732,0.052820,NaN,NaN
2,0004837f0c785928a29a6f83f70f4a1c54caec483a773f...,0.638958,0.634894,0.642295,1.916874,0.640140,0.628740,0.663800,3.840840,0.656560,...,0.003735,0.000057,0.008431,0.033616,0.004333,0.000057,0.008884,0.051998,NaN,NaN
3,0004ec03ca1ab2adb9aa260c61ba5dce8185e19d3ab704...,0.973429,0.963991,0.980221,2.920287,0.970996,0.963991,0.980221,5.825976,0.970050,...,0.005166,0.000411,0.009696,0.046498,0.005340,0.000411,0.009780,0.064079,NaN,NaN
4,00050d84c6d26e26cd2b18c3eed83d3130c270e2361470...,0.993352,0.968914,1.006598,2.980056,0.973982,0.921563,1.006598,5.843892,0.963556,...,0.006437,0.001299,0.009614,0.057929,0.005899,0.000516,0.009614,0.070782,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91778,fffe2bc02423407e33a607660caeed076d713d8a5ad323...,0.407346,0.405106,0.408619,1.222039,0.483217,0.405106,0.643031,2.899303,0.513501,...,0.006129,0.001390,0.009487,0.042902,0.006129,0.001390,0.009487,0.042902,NaN,NaN
91779,ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fd...,0.842163,0.831279,0.856351,2.526490,0.854855,0.831279,0.868121,5.129130,0.856552,...,0.005744,0.002929,0.007776,0.051698,0.005659,0.002929,0.007776,0.067913,NaN,NaN
91780,ffff9984b999fccb2b6127635ed0736dda94e544e67e02...,0.793959,0.786806,0.800522,2.381876,0.794153,0.786806,0.800522,3.970766,0.791699,...,0.003957,0.000807,0.006776,0.027701,0.004173,0.000204,0.008535,0.045898,NaN,NaN
91781,ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf38814...,0.765340,0.754129,0.787439,2.296021,0.777606,0.754129,0.791680,4.665638,0.783375,...,0.186710,0.182622,0.190875,1.680386,0.186874,0.182622,0.191400,2.242486,NaN,NaN
91782,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,0.978352,0.969861,0.983019,2.935055,0.979801,0.969861,0.984907,5.878806,0.976354,...,0.006563,0.001914,0.009291,0.059068,0.005761,0.001914,0.009291,0.069136,NaN,NaN

In [52]:
# Ensure both feature sets exist
if 'df_numerical_features' not in locals():
    df_numerical_features = pd.DataFrame()

if 'df_categorical_features' not in locals():
    df_categorical_features = pd.DataFrame()

# Merge logic
if not df_numerical_features.empty and not df_categorical_features.empty:
    print("Merging numerical and categorical features...")
    df_final_features = pd.merge(
        df_numerical_features,
        df_categorical_features,
        on='customer_ID',
        how='outer'
    )
elif not df_numerical_features.empty:
    print("Using only numerical features.")
    df_final_features = df_numerical_features.copy()
elif not df_categorical_features.empty:
    print("Using only categorical features.")
    df_final_features = df_categorical_features.copy()
else:
    print("No features available. Creating empty DataFrame.")
    df_final_features = pd.DataFrame()

# OPTIONAL: Merge the target column
if 'train_date_filtered' in locals() and 'target' and 'date' in train_date_filtered.columns:
    print("Merging target column...")
    target_df = train_date_filtered[['customer_ID', 'target','date']].drop_duplicates(subset='customer_ID')
    df_final_features = pd.merge(df_final_features, target_df, on='customer_ID', how='left')
else:
    print("Warning: Could not find 'target' column in train_date_filtered.")

# Handle missing values safely, even for categorical columns
for col in df_final_features.columns:
    col_data = df_final_features[col]
    
    if pd.api.types.is_categorical_dtype(col_data):
        # Get the category type to match the fill value
        if len(col_data.cat.categories) > 0:
            cat_type = type(col_data.cat.categories[0])
            fill_value = cat_type(0)  # Convert 0 to the same type
        else:
            fill_value = 0  # fallback

        # Add category if it's not there
        if fill_value not in col_data.cat.categories:
            try:
                df_final_features[col] = col_data.cat.add_categories([fill_value])
            except ValueError:
                pass  # Already present or incompatible type

        # Now fill safely
        df_final_features[col] = df_final_features[col].fillna(fill_value)
    else:
        df_final_features[col] = col_data.fillna(0)

# Final preview
print("Final features shape:", df_final_features.shape)
df_final_features.head()

Merging numerical and categorical features...
Merging target column...

C:\Users\shrey\AppData\Local\Temp\ipykernel_2356\2367162686.py:39: DeprecationWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(col_data):

Final features shape: (91783, 3422)

,customer_ID,P_2Ave3,P_2Min3,P_2Max3,P_2Sum3,P_2Ave6,P_2Min6,P_2Max6,P_2Sum6,P_2Ave9,...,D_68_5.0Response_Rate12,D_68_5.0Ever_Response12,D_68_5.0Apr2018,D_68_6.0Response_Rate6,D_68_6.0Ever_Response6,D_68_6.0Response_Rate12,D_68_6.0Ever_Response12,D_68_6.0Apr2018,target,date
0,000098081fde4fd64bc4d503a5d6f86a0aedc425c96f52...,0.447801,0.414444,0.477116,1.343404,0.453994,0.407172,0.560474,2.723962,0.472079,...,0.000000,False,0,0.0,False,0.000000,False,0,0,2017-03-11
1,000445609ff2a39d2dd02484899affa5696210a95f6869...,0.976846,0.974383,0.978897,2.930539,0.972001,0.949051,0.986043,5.832008,0.971372,...,0.000000,False,0,1.0,True,1.000000,True,0,0,2017-03-10
2,0004837f0c785928a29a6f83f70f4a1c54caec483a773f...,0.638958,0.634894,0.642295,1.916874,0.640140,0.628740,0.663800,3.840840,0.656560,...,1.000000,True,0,0.0,False,0.000000,False,0,0,2017-03-01
3,0004ec03ca1ab2adb9aa260c61ba5dce8185e19d3ab704...,0.973429,0.963991,0.980221,2.920287,0.970996,0.963991,0.980221,5.825976,0.970050,...,0.583333,True,0,0.0,False,0.416667,True,0,0,2017-03-09
4,00050d84c6d26e26cd2b18c3eed83d3130c270e2361470...,0.993352,0.968914,1.006598,2.980056,0.973982,0.921563,1.006598,5.843892,0.963556,...,0.000000,False,0,1.0,True,1.000000,True,0,0,2017-03-14

In [2]:
df_final_features.to_csv("02_Features_final.csv", index=False)

NameError: name 'df_final_features' is not defined

In [3]:
df_final_features = pd.read_csv('02_Features_final.csv')

In [4]:
import pandas as pd
import re

# Use your actual DataFrame name here — should be the one after one-hot encoding
# Example: df_encoded = pd.get_dummies(df, columns=categorical_columns)
# Make sure df_encoded is already defined in your code

# Define feature category patterns based on naming conventions
category_patterns = {
    'Delinquency': r'^D_',
    'Balance': r'^B_',
    'Risk': r'^R_',
    'Spend': r'^S_',
    'Payment': r'^P_',
    'Date': r'^S_2$',  # Specific for timestamp column
    'Customer Info': r'^customer_ID$',
    'Unknown/Other': r'^.*'  # Catch-all fallback
}

# Initialize dictionary to hold counts
category_counts = {cat: 0 for cat in category_patterns}

# Categorize and count columns
for col in df_final_features.columns:
    matched = False
    for category, pattern in category_patterns.items():
        if re.match(pattern, col):
            category_counts[category] += 1
            matched = True
            break
    if not matched:
        category_counts['Unknown/Other'] += 1

# Convert result to DataFrame for display or export
category_summary = pd.DataFrame.from_dict(category_counts, orient='index', columns=['# Columns'])
category_summary.index.name = 'Feature Category'

# Display the result
print(category_summary)

# Optional: Save to CSV
# category_summary.to_csv('feature_category_counts.csv')

                  # Columns
Feature Category
Delinquency            1749
Balance                 734
Risk                    504
Spend                   378
Payment                  54
Date                      0
Customer Info             1
Unknown/Other             2